### ISSUE TITLE
change dependency from psycopg2 to psycopg2-binary

### ISSUE THREAD

**Issue by ShukriChiu** [timescale/python-vector#15]
I want to deploy a Streamlit app, but I encountered an error: 'Error: pg_config executable not found,' while trying to install psycopg2. Although I switched to psycopg2-binary, the dependency on timescale-vector still requires psycopg2, which continues to cause a deployment error.

**Comment by mcr-kaes** [comment]
I am running into the same issue when I build a docker container.

**Comment by jgpruitt** [comment]
The timescale-vector package explicitly depends on psycopg2 (the non-binary version). This adheres to the [advice provided by psycopg2](https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary):
```
If you are the maintainer of a published package depending on psycopg2 you shouldn’t use psycopg2-binary as a module dependency. For production use you are advised to use the source distribution.
```

Building psycopg from source [requires a few prerequisites to be installed](https://www.psycopg.org/docs/install.html#build-prerequisites). Make sure these are installed before trying to `pip install timescale-vector`

**Comment by cevian** [comment]
@ShukriChiu I believe you may need to add `libpq-dev` to packages.txt at the root of your streamlit app.

@mcr-kaes Similarly try running `apt install libpq-dev`

**Comment by jgpruitt** [comment]
Add this information to the README
